[package]
org = "choreo"
displayName = "COVID-19 Statistics to Email"
name = "covid19_statistics_to_email"
description = "Calculates COVID-19 cases per million in a specific country and send an email"
distribution = "2201.3.1"
version = "1.0.0"
[build-options]
observabilityIncluded = true